---
# APT Config
- name: Configure apt to use Cloudflare mirror
  ansible.builtin.replace:
    path: /etc/apt/sources.list
    regexp: '^(deb\s+)http://([A-Za-z0-9.-]+)(/kali.*)$'
    replace: '\1http://kali.download\3'

- name: Install apt packages to support HTTPS repos
  package:
    name:
      - apt-utils
      - ca-certificates
      - apt-transport-https
    state: latest
  become: true
  become_method: sudo

- name: Configure apt to use HTTPS for Kali repo
  ansible.builtin.replace:
    path: /etc/apt/sources.list
    regexp: '^(deb\s+)http://(.*)$'
    replace: '\1https://\2'
