---
- name: Ensure apt-transport-https is installed
  apt:
    name: apt-transport-https
    state: present
  become: true

- name: Add Docker GPG key
  block:
  - name: Download Docker GPG key
    get_url:
      url: https://download.docker.com/linux/debian/gpg
      dest: /tmp/docker.gpg
      mode: '0644'
    become: true

  - name: Remove existing Docker GPG key if present
    file:
      path: /etc/apt/keyrings/docker.gpg
      state: absent
    become: true

  - name: De-armor Docker GPG key
    command: gpg --dearmor -o /etc/apt/keyrings/docker.gpg /tmp/docker.gpg
    args:
      creates: /etc/apt/keyrings/docker.gpg
    become: true

  - name: Clean up temporary key file
    file:
      path: /tmp/docker.gpg
      state: absent
    become: true

- name: Add Docker repository to sources.list.d
  copy:
    content: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian {{ kali_debian_distro }} stable"
    dest: /etc/apt/sources.list.d/docker.list
    mode: '0644'
  become: true

- name: Update apt cache
  apt:
    update_cache: yes
  become: true

- name: Update apt and install docker-ce
  package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest
  become: true
  become_method: sudo

- name: Increase max_map_count kernel parameter
  sysctl:
    name: vm.max_map_count
    value: 262144
    state: present
    reload: yes
  become: yes

- name: Increase fs.file-max
  sysctl:
    name: fs.file-max
    value: 1048576
    state: present
    reload: yes
  become: yes
