---
- name: "Kali Ansible playbook"
  hosts: localhost
  connection: local
  vars:
    users:
      - username: "{{ ansible_user_id }}"
  roles:
    - role: "roles/install-tools"
    - role: "roles/docker"

- name: Include Kali packages playbook
  ansible.builtin.import_playbook: kali-packages.yml
