---
- name: "Kali Ansible playbook"
  hosts: localhost
  connection: local
  become: true
  vars:
    users:
      - username: "{{ ansible_user_id }}"
  roles:
    - role: install-tools
    - role: gantsign.visual-studio-code # install VSCode - https://github.com/gantsign/ansible-role-visual-studio-code
      users:
        - username: "{{ ansible_env.SUDO_USER }}"
          visual_studio_code_extensions:
            - streetsidesoftware.code-spell-checker
            - wholroyd.jinja
            - ms-python.python
